# Generated by Django 4.1.3 on 2023-11-02 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plugin', models.BooleanField()),
                ('compute', models.BooleanField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
