# Generated by Django 4.1.3 on 2023-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_models", "0002_rename_mymodel_connectionstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionstatus",
            name="compute",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="connectionstatus",
            name="plugin",
            field=models.BooleanField(default=False),
        ),
    ]
