# Generated by Django 4.1.3 on 2023-11-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_models", "0008_alter_byocmessagestate_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="byocmessagestate",
            name="request",
            field=models.JSONField(),
        ),
    ]
