# Generated by Django 5.0.1 on 2024-01-30 01:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0009_alter_byocmessagestate_request"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("master_token", models.UUIDField()),
                ("connection_token", models.UUIDField(unique=True)),
                ("connection_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
