# Generated by Django 5.0.3 on 2024-04-07 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "game_models",
            "0014_remoteimage_processor_remotesource_processor_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectionstatus",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="connectionstatus",
            name="compute_updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="connectionstatus",
            name="plugin_updated_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
