# Generated by Django 5.0.3 on 2024-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0016_connectionstatus_loaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="connection_type",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
