# Generated by Django 5.0.3 on 2024-05-01 20:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0019_gamemapstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                ("game_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("level", models.IntegerField()),
                ("aesthetic", models.CharField(max_length=1024)),
                ("map_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
