# Generated by Django 5.0.3 on 2024-05-01 21:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0020_gamestate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gamestate",
            name="game_id",
        ),
    ]
