# Generated by Django 5.0.3 on 2024-05-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0023_gameelementlookup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameelementlookup",
            name="element_id",
            field=models.UUIDField(primary_key=True, serialize=False, unique=True),
        ),
    ]
