# Generated by Django 5.0.3 on 2024-05-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0025_gameinventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="environment_img",
            field=models.CharField(
                default="https://storage.googleapis.com/byoc-file-transfer/img_placeholder.png",
                max_length=1024,
            ),
            preserve_default=False,
        ),
    ]
