# Generated by Django 5.0.3 on 2024-05-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0027_gameinventory_map_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameUpdateQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField(unique=True)),
                ("level", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("started", "Started"),
                            ("completed", "Completed"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
