# Generated by Django 5.0.3 on 2024-06-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0031_alter_gameevent_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemapstate",
            name="aesthetic",
            field=models.CharField(
                default="Traditional fantasy with elves, dwarfs, Orcs", max_length=1024
            ),
            preserve_default=False,
        ),
    ]
