# Generated by Django 5.0.3 on 2024-06-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0034_alter_gamestate_map_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameevent",
            name="payload",
            field=models.JSONField(default="{}"),
            preserve_default=False,
        ),
    ]
