# Generated by Django 5.0.3 on 2024-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_models", "0035_gameevent_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameevent",
            name="payload",
            field=models.JSONField(default=dict),
        ),
    ]
