# Generated by Django 5.0.3 on 2024-07-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_models", "0038_gamestate_art_style_gamestate_setting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BYOCMessageState",
        ),
        migrations.DeleteModel(
            name="ComputeContract",
        ),
        migrations.DeleteModel(
            name="Connection",
        ),
        migrations.DeleteModel(
            name="ConnectionStatus",
        ),
        migrations.DeleteModel(
            name="RemoteImage",
        ),
        migrations.DeleteModel(
            name="RemoteSource",
        ),
    ]
