FROM python:3.10-slim

LABEL maintainer=pierrick.libert@gmail.com

RUN apt-get update && apt-get upgrade -y && apt-get install -y gcc git curl postgresql postgresql-client libpq-dev && apt-get clean -y
COPY requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /cms
# Copy the rest of the files
COPY . /cms

ENTRYPOINT ["sh", "setup.sh", "8082"]
