# Generated by Django 4.1.3 on 2023-11-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('byo_network_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='ConnectionStatus',
        ),
    ]
