# Generated by Django 4.1.3 on 2023-11-03 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('byo_network_hub', '0003_alter_connectionstatus_compute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputeContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
