# Generated by Django 4.1.3 on 2023-11-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byo_network_hub', '0005_byocmessagestate_alter_computecontract_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byocmessagestate',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
