# Generated by Django 4.1.3 on 2023-11-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('byo_network_hub', '0006_alter_byocmessagestate_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='byocmessagestate',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
