# Generated by Django 5.0.1 on 2024-03-06 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0011_remoteimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("remote_name", models.CharField(max_length=100)),
                ("remote_description", models.CharField(max_length=250)),
                ("remote_category", models.CharField(max_length=100)),
                ("remote_author", models.CharField(max_length=100)),
                ("source_url", models.CharField(max_length=1500)),
                ("remote_version", models.CharField(default="v0", max_length=25)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
