# Generated by Django 5.0.3 on 2024-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0021_remove_gamestate_game_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="environment_id",
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
