# Generated by Django 5.0.3 on 2024-05-02 21:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0024_alter_gameelementlookup_element_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField()),
                ("item_id", models.UUIDField()),
                ("item_details", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
