# Generated by Django 5.0.3 on 2024-05-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0026_gamestate_environment_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameinventory",
            name="map_id",
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
