# Generated by Django 5.0.3 on 2024-06-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0029_alter_gameupdatequeue_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.UUIDField()),
                (
                    "event",
                    models.CharField(
                        choices=[("levelup", "LevelUp"), ("combat", "Combat")],
                        default="combat",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
