# Generated by Django 5.0.3 on 2024-06-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0030_gameevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("level-up-ready", "LevelUpReady"),
                    ("level-up-complete", "LevelUpComplete"),
                    ("encounter-start", "EncounterStart"),
                    ("encounter-victory", "EncounterVictory"),
                    ("encounter-loss", "EncounterLoss"),
                    ("inventory-update", "InventoryUpdate"),
                ],
                default="combat",
                max_length=32,
            ),
        ),
    ]
