# Generated by Django 5.0.3 on 2024-06-18 20:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("byo_network_hub", "0036_alter_gameevent_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamestate",
            name="map_id",
            field=models.UUIDField(
                blank=True,
                default=uuid.UUID("00000000-0000-0000-0000-000000000000"),
                null=True,
            ),
        ),
    ]
