# Generated by Django 5.0.3 on 2024-07-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("byo_network_hub", "0037_alter_gamestate_map_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="art_style",
            field=models.CharField(default="watercolor painting", max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="gamestate",
            name="setting",
            field=models.CharField(default="", max_length=4096),
            preserve_default=False,
        ),
    ]
