'''
This is to disable the default 404 'Not Found' message which is
generated by Django.
'''
import logging


# pylint: disable=too-few-public-methods
class NotFoundFilter(logging.Filter):
    '''This filter has to be configured in settings/base.py'''

    def filter(self, record: logging.LogRecord) -> bool:
        '''Return a formatted message'''
        return '%s: %s' not in record.msg
